#%RAML 1.0 NamedExample
  {
    "current_timestamp": "2023-06-03T15:33:03Z",
    "base_value": "EUR",
    "requested_value": {
    "INR": 88.382546
      },
    "status": "success",
    "code": 200
  }